spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/Anabada
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: true

  h2:
    console:
      enabled=true:

  session:
    store-type: jdbc
  profiles:
    active: local

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

--- # prod 환경
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/anabada?useSSL=false&characterEncoding=UTF-8&serverTimeZone=UTC
    username: anabada
    password: anabada
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: info

server:
  port: 8089

---