spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/Anabada
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: flase
        format_sql: true

  h2:
    console:
      enabled=true:

  session:
    store-type: jdbc
  profiles:
    active: local

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace